spring:
  application:
    name: memorial_application
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${JDBC_DRIVER_SOURCE}
    url: ${DB_URL}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect


server:
  port:
    ${SERVER_PORT}


grpc:
  client:
    anime-server:
      address: ${GRPC_ANIME_SERVER_ADDRESS}
      negotiationType: "plaintext"



kafka:
  bootstrap-servers: ${KAFKA_URL}
  schema-registry-url: ${SCHEMA_REGISTRY_URL}
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL}
      auto.register.schemas: true
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      specific-avro-reader: true
logging:
  level:
    com.example.memorial_application: trace
